### ISSUE TITLE
Edit please

### ISSUE THREAD

**Issue by Danilwsk** [WeekThor/AdminProtect#2]
Please change the ban method for a while: /tempban Steve 15 cheat Steve banned 15 days Reason: cheat That is, remove the blocking date and set the blocking in days

**Comment by WeekThor** [comment]
Hi,
Since AdminProtect v2.0.0 beta 3 there are 3 ways to ban for a while:
- Specify the ban end date in dd.mm.YYYY (`/tempban Steve 15.02.2022 cheat`)
- Specify the ban duration in special format (`/tempban Steve 1mo3d cheat`, where `1mo3d` means 1 month and 15 days)
- Specify the ban duration in days (`/tban Steve 15 cheat` will ban Steve for 15 days)

In older versions only first and second methods existed. So, to ban Steve for 15 days you can use `/tempban Steve 15d cheat`.
